name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue. The developer team will work on solving it as soon as possible.'
        pr-message: 'Thank you for submitting a pull request. The developer team will be reviewing it as soon as possible.'
